name: Opengrep

# Workflow disabled - uncomment to re-enable
on:
   push:
     branches: [ main, master ]
   pull_request:
     branches: [ main, master ]
   workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
   opengrep:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout code
           uses: actions/checkout@v4
           
         - name: Run Opengrep SAST scan
           run: |
            wget https://github.com/opengrep/opengrep/releases/download/latest/opengrep_manylinux_x86 -O opengrep
            chmod +x opengrep
            ./opengrep ci --sarif --sarif-output opengrep_report.sarif --config auto --supress-errors

         - name: Upload SARIF to Code Scanning
           uses: github/codeql-action/upload-sarif@v3
           with:
                sarif_file: opengrep_report.sarif
